### ISSUE TITLE
[Issue] incorrect calculation (or labelling) of „Felix+.01“ metric

### ISSUE THREAD

**Issue by fnschmidt** [felikan/Umrecheninator#1]
An input value of "1,5" yields a result of 1 Felix.
at the same time, an input of "1,6" translates to 1 "Felix+.01".

This, clearly, is in violation of the laws of arithmetics.

According to all known laws of mathematics, there is no way Felix+0.01 should be able to be "Felix"+.1. 
The Umrecheninator, of course, does this anyway because it doesn’t care what math thinks is impossible.

Valve, pls fix.

**Comment by felikan** [comment]
wrong repo.
